include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - nonfunction-type-aliases

linter:
  rules:
    - prefer_final_locals
    # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - always_declare_return_types
    - prefer_single_quotes
    - unawaited_futures
    - unsafe_html